/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib\theme.ts
 * Command: astryx theme build lib\theme.ts --out lib\theme.generated.css
 * Generated: 2026-08-27T17:42:14.836Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
