/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib\theme.ts
 * Command: astryx theme build lib\theme.ts --out lib\theme.generated.css
 * Generated: 2026-08-27T17:42:14.782Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const danielPortfolioTheme: DefinedTheme;
